import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { ApiError, createParcelVersion, type Parcel, type ParcelVersionSaveResult } from "../api/gis";
import { geodesicAreaM2, percentDifference, squareFeet } from "../features/gis/geometry";
import { useParcelEditor } from "../features/gis/useParcelEditor";

type Editor = ReturnType<typeof useParcelEditor>;
const number = (value: number | null) => value === null ? "Not available" : new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value);

export function ParcelEditor({ projectId, parcel, editor, canEdit, onSaved }: { projectId: string; parcel: Parcel; editor: Editor; canEdit: boolean; onSaved: (result: ParcelVersionSaveResult) => void }) {
  const [changeReason, setChangeReason] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [clientChecked, setClientChecked] = useState(false);
  const mutation = useMutation({ mutationFn: () => createParcelVersion(projectId, parcel.id, { geometry: editor.session!.working, expected_current_version: editor.session!.expectedCurrentVersion, change_reason: changeReason.trim() }), onSuccess: (result) => { editor.saved(); onSaved(result); }, onError: (error) => setNotice(error instanceof ApiError && error.code === "PARCEL_VERSION_CONFLICT" ? "This parcel changed while you were editing. Refresh the parcel before saving another draft." : error instanceof Error ? error.message : "The draft could not be saved.") });
  const geometry = parcel.current_version.geometry;

  if (!editor.session) return <section className="parcel-editor" aria-label="Parcel editing controls">{!canEdit && <p className="panel-note">You have read-only access. `geo:edit_draft` is required to edit this draft boundary.</p>}{geometry === null && <p className="error-copy">Geometry is not determined, so this parcel cannot enter standard edit mode.</p>}{geometry?.type === "MultiPolygon" && <p className="error-copy">MultiPolygon editing is disabled in this D.2 MVP; the geometry remains read-only.</p>}{geometry?.type === "Polygon" && geometry.coordinates.length > 1 && <p className="error-copy">Polygon geometries with interior rings are read-only in this D.2 MVP.</p>}{canEdit && geometry?.type === "Polygon" && geometry.coordinates.length === 1 && <button type="button" className="primary-action" onClick={() => { const error = editor.enter(parcel); setNotice(error); }}>Edit Boundary</button>}{notice && <p className="error-copy" role="alert">{notice}</p>}</section>;

  const originalArea = parcel.current_version.area_m2 ?? geodesicAreaM2(editor.session.original); const editedArea = geodesicAreaM2(editor.session.working); const problems = editor.problems;
  return <section className="parcel-editor edit-mode" aria-label="Parcel editing controls"><p className="edit-banner">Edit mode · Draft parcel geometry requires authorized verification.</p><div className="editor-actions"><button type="button" onClick={editor.undo} disabled={editor.session.historyIndex === 0}>Undo</button><button type="button" onClick={editor.redo} disabled={editor.session.historyIndex === editor.session.history.length - 1}>Redo</button><button type="button" onClick={editor.reset}>Reset</button><button type="button" onClick={editor.toggleOriginal}>{editor.session.showOriginal ? "Hide Original" : "Show Original"}</button><button type="button" onClick={() => setNotice(editor.deleteSelectedVertex())}>Delete selected vertex</button></div><p className="panel-note">Drag a handle to move it. Click the edited boundary to add a vertex, then select a handle before deletion.</p><div className="area-comparison"><div><strong>Original area</strong><span>{number(originalArea)} m² · {number(squareFeet(originalArea))} sq ft</span></div><div><strong>Edited area</strong><span>{number(editedArea)} m² · {number(squareFeet(editedArea))} sq ft</span></div><div><strong>Difference</strong><span>{number(editedArea === null || originalArea === null ? null : editedArea - originalArea)} m² · {number(percentDifference(originalArea, editedArea))}%</span></div></div><button type="button" onClick={() => setClientChecked(true)}>Validate geometry</button>{clientChecked && <p className={problems.length ? "error-copy" : "success-copy"}>{problems.length ? problems.join(" ") : "Basic client checks passed. C.6 validation runs authoritatively when the draft is saved."}</p>}{notice && <p className="error-copy" role="alert">{notice}</p>}<label className="reason-field">Change reason<textarea value={changeReason} onChange={(event) => setChangeReason(event.target.value)} maxLength={2000} placeholder="Adjusted eastern boundary based on field verification" /></label><div className="editor-actions"><button type="button" className="primary-action" disabled={!changeReason.trim() || Boolean(problems.length) || mutation.isPending} onClick={() => { setNotice(null); mutation.mutate(); }}>Save Draft</button><button type="button" onClick={editor.cancel} disabled={mutation.isPending}>Cancel</button></div>{mutation.isPending && <p>Saving draft and running server validation…</p>}</section>;
}
