import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import { DocumentsPage } from "../pages/DocumentsPage";

const user = { id: "user", permissions: ["document:read", "document:upload", "document:process", "field:read", "field:correct"], project_memberships: [{ project_id: "project", role: "OFFICER" }] };
function installFetch(readOnly = false) { vi.stubGlobal("fetch", vi.fn(async (input: RequestInfo | URL) => { const url = String(input); if (url.includes("/users/me")) return new Response(JSON.stringify(readOnly ? { ...user, permissions: ["document:read", "field:read"] } : user)); if (url.endsWith("/documents")) return new Response(JSON.stringify({ items: [{ id: "doc", project_id: "project", filename: "record.pdf", content_type: "application/pdf", size_bytes: 1, status: "REVIEW_REQUIRED", latest_processing_job_id: null, uploaded_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" }] })); if (url.endsWith("/documents/doc")) return new Response(JSON.stringify({ id: "doc", project_id: "project", filename: "record.pdf", content_type: "application/pdf", size_bytes: 1, status: "REVIEW_REQUIRED", latest_processing_job_id: null, uploaded_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z", latest_ocr: null, latest_validation: null })); if (url.endsWith("/documents/doc/fields")) return new Response(JSON.stringify({ fields: [] })); return new Response("{}", { status: 404 }); })); }
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={["/projects/project/documents"]}><Routes><Route path="/projects/:projectId/documents" element={<DocumentsPage />} /></Routes></MemoryRouter></QueryClientProvider>); }
afterEach(() => vi.restoreAllMocks());
describe("DocumentsPage", () => { it("renders a document and its preliminary review state", async () => { installFetch(); renderPage(); expect(await screen.findByText("record.pdf")).toBeInTheDocument(); expect(screen.getByText("REVIEW_REQUIRED")).toBeInTheDocument(); expect(screen.getByText(/preliminary evidence/i)).toBeInTheDocument(); }); it("hides upload controls for read-only users", async () => { installFetch(true); renderPage(); await screen.findByText("record.pdf"); expect(screen.queryByRole("button", { name: /upload document/i })).not.toBeInTheDocument(); }); });
