import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { ApiError, loadGisProject, loadParcelVersions, type GeoFeature, type Parcel } from "../api/gis";
import { GisMap, type LayerVisibility, type MapFeatureKind } from "../components/GisMap";

const initialLayers: LayerVisibility = { basemap: true, parcels: true, buildings: true, roads: true, landUse: true, topology: true };
const measure = (value: number | null) => value === null ? "Not available" : new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value);

function ParcelPanel({ projectId, parcel, issueCount }: { projectId: string; parcel: Parcel | null; issueCount: number }) {
  const versions = useQuery({ queryKey: ["parcel-versions", projectId, parcel?.id], queryFn: () => loadParcelVersions(projectId, parcel!.id), enabled: Boolean(parcel) });
  if (!parcel) return <aside className="detail-panel empty-panel"><h2>Feature details</h2><p>Select a parcel boundary to inspect its draft metadata. Building footprints remain separate from parcel boundaries.</p></aside>;
  const version = parcel.current_version;
  return <aside className="detail-panel" aria-label="Parcel details"><p className="eyebrow">Draft parcel</p><h2>{parcel.external_identifier ?? parcel.id}</h2><div className="status-row"><span>{parcel.status}</span><span>{parcel.verification_status}</span>{parcel.ai_boundary_status && <span>{parcel.ai_boundary_status}</span>}</div><dl><dt>Parcel ID</dt><dd>{parcel.id}</dd><dt>Source</dt><dd>{parcel.source}</dd><dt>Source reference</dt><dd>{parcel.source_reference ?? "Not supplied"}</dd><dt>Current version</dt><dd>{parcel.current_geometry_version}</dd><dt>Source CRS</dt><dd>{parcel.source_crs ?? "No declared CRS"}</dd><dt>Processed at</dt><dd>{version.processed_at ? new Date(version.processed_at).toLocaleString() : "Not supplied"}</dd><dt>Confidence</dt><dd>{parcel.confidence === null ? "Not available" : `${Math.round(parcel.confidence * 100)}%`}</dd><dt>Model version</dt><dd>{parcel.model_version ?? "Not applicable"}</dd><dt>Area</dt><dd>{measure(version.area_m2)} m²</dd><dt>Area</dt><dd>{measure(version.area_sqft)} sq ft</dd><dt>Survey required</dt><dd>{parcel.requires_survey ? "Yes" : "No"}</dd><dt>Topology issues</dt><dd><strong className={issueCount ? "issue-count" : ""}>{issueCount}</strong></dd></dl><h3>Version history</h3>{versions.isLoading && <p>Loading versions…</p>}{versions.isError && <p className="error-copy">Version history is unavailable.</p>}{versions.data && <ol className="version-list">{versions.data.map((item) => <li key={item.id}><strong>v{item.version}</strong><span>{item.created_by_type} · {item.created_by_user_id ?? "system"} · {new Date(item.created_at).toLocaleDateString()}</span><span>{measure(item.area_m2)} m² · {measure(item.area_sqft)} sq ft</span><span>{item.source} · {item.source_reference ?? "No source reference"}</span>{item.change_reason && <span>{item.change_reason}</span>}</li>)}</ol>}<button type="button" disabled>View version history</button><p className="panel-note">Read-only in D.1. D.2 will create a new draft version without overwriting this geometry.</p></aside>;
}

function FeaturePanel({ kind, feature }: { kind: MapFeatureKind; feature: GeoFeature | null }) {
  if (!feature) return <aside className="detail-panel empty-panel"><h2>Feature details</h2><p>The selected GIS feature is no longer available.</p></aside>;
  const title = kind === "ROAD" ? String(feature.properties.road_class ?? "Road or pathway") : kind === "LAND_USE" ? String(feature.properties.land_use_class ?? "Land use") : "Building footprint";
  return <aside className="detail-panel" aria-label={`${kind.toLowerCase()} details`}><p className="eyebrow">{kind.replace("_", " ")}</p><h2>{title}</h2><div className="status-row"><span>{feature.status}</span><span>{feature.verification_status}</span></div><dl><dt>Feature ID</dt><dd>{feature.id}</dd><dt>Source</dt><dd>{feature.source}</dd><dt>Source reference</dt><dd>{feature.source_reference ?? "Not supplied"}</dd><dt>Confidence</dt><dd>{feature.confidence === null ? "Not available" : `${Math.round(feature.confidence * 100)}%`}</dd><dt>Model version</dt><dd>{feature.model_version ?? "Not applicable"}</dd><dt>Processed at</dt><dd>{feature.processed_at ? new Date(feature.processed_at).toLocaleString() : "Not supplied"}</dd>{kind === "ROAD" && <><dt>Length</dt><dd>{measure(feature.properties.length_m as number | null)} m</dd></>}{kind !== "ROAD" && <><dt>Area</dt><dd>{measure(feature.properties.area_m2 as number | null)} m²</dd><dt>Area</dt><dd>{measure(feature.properties.area_sqft as number | null)} sq ft</dd></>}</dl><p className="panel-note">Read-only GIS context. This feature is not a legal parcel determination.</p></aside>;
}

export function GisPage() {
  const { projectId } = useParams(); const [layers, setLayers] = useState(initialLayers); const [selected, setSelected] = useState<{ kind: "PARCEL" | MapFeatureKind; id: string } | null>(null);
  const query = useQuery({ queryKey: ["gis-project", projectId], queryFn: () => loadGisProject(projectId!), enabled: Boolean(projectId) });
  if (!projectId) return <main className="gis-state"><h1>Project GIS unavailable</h1></main>;
  if (query.isLoading) return <main className="gis-state"><p className="eyebrow">Web-GIS</p><h1>Loading project layers…</h1></main>;
  if (query.isError) { const error = query.error as ApiError; const message = error.status === 403 ? "You do not have permission to view this project’s GIS layers." : error.status === 401 ? "Sign in with a session that has geo:read permission." : error.status === 404 ? "This project or its GIS data was not found." : "The GIS layers could not be loaded."; return <main className="gis-state"><p className="eyebrow">Web-GIS</p><h1>Map unavailable</h1><p>{message}</p><Link to="/">Return to platform</Link></main>; }
  const data = query.data!; const selectedParcel = selected?.kind === "PARCEL" ? data.parcels.find((parcel) => parcel.id === selected.id) ?? null : null; const selectedFeature = selected?.kind === "BUILDING" ? data.buildings.find((item) => item.id === selected.id) ?? null : selected?.kind === "ROAD" ? data.roads.find((item) => item.id === selected.id) ?? null : selected?.kind === "LAND_USE" ? data.landUse.find((item) => item.id === selected.id) ?? null : null; const issues = selectedParcel ? data.topology.filter((issue) => issue.parcel_id === selectedParcel.id || issue.related_parcel_id === selectedParcel.id).length : 0; const empty = !data.parcels.length && !data.buildings.length && !data.roads.length && !data.landUse.length;
  const topologyParcelIds = [...new Set(data.topology.flatMap((issue) => [issue.parcel_id, issue.related_parcel_id]).filter((id): id is string => Boolean(id)))];
  return <main className="gis-shell"><header className="gis-header"><div><p className="eyebrow">Project Web-GIS · D.1</p><h1>Project cadastral viewer</h1><p>Project: {projectId}</p></div><div className="layer-controls" aria-label="Layer controls">{(Object.keys(layers) as Array<keyof LayerVisibility>).map((key) => <label key={key}><input aria-label={key === "landUse" ? "land use" : key} type="checkbox" checked={layers[key]} onChange={() => setLayers((current) => ({ ...current, [key]: !current[key] }))} /> {key === "landUse" ? "Land use" : key}</label>)}</div></header><section className="gis-workspace"><div className="map-column"><GisMap parcels={data.parcels} buildings={data.buildings} roads={data.roads} landUse={data.landUse} topologyParcelIds={topologyParcelIds} visibility={layers} selectedParcelId={selected?.kind === "PARCEL" ? selected.id : null} onParcelSelect={(id) => setSelected({ kind: "PARCEL", id })} onFeatureSelect={(kind, id) => setSelected({ kind, id })} />{empty && <div className="map-empty">No GIS features are available for this project yet.</div>}<div className="map-legend"><strong>Land use</strong><span>Residential/commercial/industrial: amber · Agricultural: ochre · Water: blue · Green: green · Unknown: neutral</span><span>Parcels are draft/preliminary. Buildings are not parcel boundaries. Red dashes flag linked unresolved topology findings.</span></div></div>{selected?.kind === "PARCEL" || !selected ? <ParcelPanel projectId={projectId} parcel={selectedParcel} issueCount={issues} /> : <FeaturePanel kind={selected.kind} feature={selectedFeature} />}</section></main>;
}
